[2022-03-22 06:42:22,403] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fifa_player_dag.upload_to_gcs_job 2022-03-22T06:42:16.884979+00:00 [queued]>
[2022-03-22 06:42:22,446] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fifa_player_dag.upload_to_gcs_job 2022-03-22T06:42:16.884979+00:00 [queued]>
[2022-03-22 06:42:22,448] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-22 06:42:22,449] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-03-22 06:42:22,450] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-22 06:42:22,478] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): upload_to_gcs_job> on 2022-03-22T06:42:16.884979+00:00
[2022-03-22 06:42:22,487] {standard_task_runner.py:52} INFO - Started process 4421 to run task
[2022-03-22 06:42:22,498] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'fifa_player_dag', 'upload_to_gcs_job', '2022-03-22T06:42:16.884979+00:00', '--job-id', '108', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/311_download_ingest_gcs.py', '--cfg-path', '/tmp/tmpfvpqg40g', '--error-file', '/tmp/tmpcp5wl8ga']
[2022-03-22 06:42:22,505] {standard_task_runner.py:77} INFO - Job 108: Subtask upload_to_gcs_job
[2022-03-22 06:42:22,598] {logging_mixin.py:104} INFO - Running <TaskInstance: fifa_player_dag.upload_to_gcs_job 2022-03-22T06:42:16.884979+00:00 [running]> on host a920a86f34d9
[2022-03-22 06:42:22,704] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=fifa_player_dag
AIRFLOW_CTX_TASK_ID=upload_to_gcs_job
AIRFLOW_CTX_EXECUTION_DATE=2022-03-22T06:42:16.884979+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-22T06:42:16.884979+00:00
[2022-03-22 06:42:22,833] {taskinstance.py:1455} ERROR - [Errno 2] No such file or directory: '/opt/airflow/*.csv'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/311_download_ingest_gcs.py", line 42, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 2473, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/*.csv'
[2022-03-22 06:42:22,852] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=fifa_player_dag, task_id=upload_to_gcs_job, execution_date=20220322T064216, start_date=20220322T064222, end_date=20220322T064222
[2022-03-22 06:42:22,919] {local_task_job.py:146} INFO - Task exited with return code 1
